<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
$_soldHelper = $this->helper('Magiccart\Alothemes\Helper\Sold');
?>
<div class="mage-magictabs timer-product mc-<?php echo $this->getTypeFilter();?>">
<?php $total = $_productCollection->count() ?>
<?php if (!$total): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $pos = $block->getPositioned();
    ?>
    <?php 
        $config     = $this->getWidgetCfg(); 
        // $width      = $config['widthImages'];
        // $height     = $config['heightImages'];
        $showCart       = $config['cart'];
        $showCompare    = $config['compare'];
        $showWishlist   = $config['wishlist'];
        $showReview     = $config['review'];
        $divisor        = ($total >= 9 ) ? 9 : 5;
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div class="products list items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php  $itemBig = ($iterator%9==5) ? 'product-big' : '' ?>
                <?php  $itemSmall = ($iterator%9==1 || $iterator%9 == 6) ? 'product-small' : '' ?>
                <?php if($iterator%9==1 || $iterator%9==5 || $iterator%9 == 6) echo "<div class='$itemSmall $itemBig'>";  /* 4-1-4*/ ?>    
                <div class='sub-item item product-item'>          
                    <div class="product-item-info" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <div class="images-container">
                            <div class="special-product-label">
                                <span class="special"><strong><?php echo __('Special') ?></strong><?php echo __('Offer') ?></span>
                                <?php echo $_aloHelper->getLabels($_product); ?>
                            </div>
                            <div class="product-hover">
                                <a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?php echo $productImage->toHtml(); ?>
                                </a>
                            </div>
                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                            <div class="hover-box">
                                <div class="product actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                
                                                <form data-role="tocart-form" action="<?php  echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey')?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary button btn-cart">
                                                            <i class="icon icon-add-to-cart"></i>
                                                            <span><?php echo __('Add to Cart') ?>
                                                        </span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($showWishlist || $showCompare): ?>
                                        <div data-role="add-to-links" class="actions-secondary add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                            <?php if ($showCompare):
                                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                ?>
                                                <a href="#"
                                                class="action tocompare"
                                                title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                                role="button">
                                                    <i class="icon icon-compare"></i><?php echo __('Compare') ?>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#"
                                                class="action towishlist"
                                                title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                data-action="add-to-wishlist"
                                                role="button">
                                                    <i class="icon icon-favorites"></i><?php echo __('Wishlist') ?>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php endif; ?>
                            <div class="product details product-item-details products-textlink">
                                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <h2 class="product-name">
                                    <a class="product-item-link" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" href="<?php echo $_product->getProductUrl() ?>">
                                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </h2>
                                <?php echo $showReview ? $block->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
                                <?php echo $block->getProductPrice($_product) ?>
                                <?php echo $block->getProductDetailsHtml($_product); ?>
                                <?php
                                    $sold   = $_soldHelper->getSoldQty($_product);
                                    $qty    = (int) $this->getProductQty($_product);
                                    $total_sale = $qty + $sold;
                                    $percent = $qty > 0 ? round(($qty/$total_sale) * 100) : 0;
                                ?>
                                <div class="product-deal-special-progress">
                                    <div class="deal-stock-label">
                                        <span class="stock-available text-left"><?php echo __('Available') ?>: <strong><?php echo $qty ?></strong></span>
                                        <span class="stock-sold text-right"><?php echo __('Already Sold') ?>: <strong><?php echo $sold ?></strong></span>
                                    </div>
                                    <div class="deal-progress">
                                        <span class="deal-progress-bar" style="width:<?php echo $percent ?>%"><?php echo $percent ?></span>
                                    </div>
                                </div>
                                <span class="slogan-countdown"><?php echo __('Hurry Up! Offer ends in:') ?></span>
                                <?php echo $_aloHelper->getTimer($_product); ?>
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                        class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php if($iterator%9==4 || $iterator%9==5 || $iterator%9 == 0 || $iterator==$total) echo '</div>'?>
                <?php $iterator++;?>
            <?php endforeach; ?>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
</div>
